import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <video
        className="fixed top-0 left-0 w-full h-full object-cover -z-10"
        src="/dream.mp4"
        autoPlay
        loop
        muted
      />
        
        {children}</body>
    </html>
  );
}
